git:
  depth: 10

language: go

matrix:
  include:
    - go: 1.13.x
      sudo: false
      env: LINTER=true GOFLAGS=-mod=vendor GO111MODULE=on
    - go: 1.13.x
      sudo: required
      services: docker
      env: TESTS=true GOFLAGS=-mod=vendor GO111MODULE=on

install:
  - make install
  - make build-test

before_script:
  - if [ "$LINTER" = true ]; then curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1; fi

script:
  - if [ "$LINTER" = true ]; then golangci-lint version && golangci-lint run; fi
  - if [ "$TESTS" = true ]; then make test; fi

